// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

import request "drone-navigation-service/app/model/request"

// LocationService is an autogenerated mock type for the LocationService type
type LocationService struct {
	mock.Mock
}

// GetLocation provides a mock function with given fields: ctx, _a1
func (_m *LocationService) GetLocation(ctx context.Context, _a1 request.LocationStringtoFloatRequest) (map[string]interface{}, error) {
	ret := _m.Called(ctx, _a1)

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(context.Context, request.LocationStringtoFloatRequest) map[string]interface{}); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, request.LocationStringtoFloatRequest) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
